baseURL = "https://akhmad.id/"
languageCode = "id-id"
defaultContentLanguage = "id"
title = "Akhmad"
theme = "akhmad"
canonifyURLs = true
relativeURLs = true
pygmentsCodefences = true
pygmentsStyle = "dracula"
paginate = 3

[params]
    description = "Cerita, Catatan, dan tulisan untuk mendokumentasikan sesuatu."
