baseURL = "https://akhmad.id/"
languageCode = "id-id"
defaultContentLanguage = "id"
title = "Akhmad"
theme = "akhmad"
canonifyURLs = true
relativeURLs = true
pygmentsCodefences = true
pygmentsStyle = "dracula"
paginate = 3

[params]
    description = "Stories, build logs, and more about my journey on tech and programming."
    title = "Akhmad Blog"
