name: Update blog posts
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Setup node v16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: TailwindCSS build production
        working-directory: ./themes/akhmad/src
        run: |
          yarn install
          yarn prod
      - name: Deploy to gh-pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.94.2
          GITHUB_ACTOR: octocat
          TARGET_REPO: rockavoldy/rockavoldy.github.io
          TARGET_BRANCH: gh-pages
          CNAME: akhmad.id
          TOKEN: ${{ secrets.TOKEN }}
