name: Update blog posts
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Setup node v16
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.94.2'
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
            version: '3.12.0'
      - name: Build hugo and Tailwindcss for production
        run: |
          task prod
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
